"""baseline: full schema as of 116-test suite

Revision ID: 26dfeebc78ce
Revises: 
Create Date: 2026-07-23 20:21:47.122417
"""
from alembic import op
import sqlalchemy as sa


revision = '26dfeebc78ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event'), ['event'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('voice_sample_path', sa.String(), nullable=True),
    sa.Column('accepted_policy_version', sa.String(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('family_circles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_family_circles_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_circles')),
    sa.UniqueConstraint('invite_code', name=op.f('uq_family_circles_invite_code'))
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('subject_kind', sa.String(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('ask_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_llm_calls_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_user_id'), ['user_id'], unique=False)

    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_resets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_resets')),
    sa.UniqueConstraint('token', name=op.f('uq_password_resets_token'))
    )
    op.create_table('product_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_product_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_events'))
    )
    with op.batch_alter_table('product_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_events_user_id'), ['user_id'], unique=False)

    op.create_table('alert_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('match', sa.JSON(), nullable=False),
    sa.Column('audience', sa.JSON(), nullable=False),
    sa.Column('severity_hint', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_alert_triggers_author_id_users')),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.id'], name=op.f('fk_alert_triggers_circle_id_family_circles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_triggers'))
    )
    op.create_table('asks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('answered_by', sa.String(), nullable=False),
    sa.Column('snippet_count', sa.Integer(), nullable=False),
    sa.Column('audio_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.id'], name=op.f('fk_asks_circle_id_family_circles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_asks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asks'))
    )
    with op.batch_alter_table('asks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asks_circle_id'), ['circle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asks_user_id'), ['user_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'circle', 'custom', name='visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_journal_entries_author_id_users')),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.id'], name=op.f('fk_journal_entries_circle_id_family_circles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries'))
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_author_id'), ['author_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.id'], name=op.f('fk_memberships_circle_id_family_circles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships'))
    )
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.id'], name=op.f('fk_relationships_circle_id_family_circles')),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_relationships_from_user_id_users')),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_relationships_to_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships'))
    )
    op.create_table('share_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('match', sa.JSON(), nullable=False),
    sa.Column('audience', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.id'], name=op.f('fk_share_rules_circle_id_family_circles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_share_rules_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_rules'))
    )
    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured', sa.JSON(), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'circle', 'custom', name='visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_facts_author_id_users')),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.id'], name=op.f('fk_facts_circle_id_family_circles')),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], name=op.f('fk_facts_entry_id_journal_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facts'))
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facts_author_id'), ['author_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_entry_id', sa.Integer(), nullable=False),
    sa.Column('source_fact_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_alerts_author_id_users')),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.id'], name=op.f('fk_alerts_circle_id_family_circles')),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_alerts_recipient_id_users')),
    sa.ForeignKeyConstraint(['source_entry_id'], ['journal_entries.id'], name=op.f('fk_alerts_source_entry_id_journal_entries')),
    sa.ForeignKeyConstraint(['source_fact_id'], ['facts.id'], name=op.f('fk_alerts_source_fact_id_facts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('share_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('fact_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], name=op.f('fk_share_targets_entry_id_journal_entries')),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], name=op.f('fk_share_targets_fact_id_facts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_share_targets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_targets'))
    )
    with op.batch_alter_table('share_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_targets_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_targets_fact_id'), ['fact_id'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('related_alert_id', sa.Integer(), nullable=True),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_actions_created_by_users')),
    sa.ForeignKeyConstraint(['related_alert_id'], ['alerts.id'], name=op.f('fk_actions_related_alert_id_alerts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions'))
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_created_by'), ['created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_created_by'))

    op.drop_table('actions')
    with op.batch_alter_table('share_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_targets_fact_id'))
        batch_op.drop_index(batch_op.f('ix_share_targets_entry_id'))

    op.drop_table('share_targets')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_recipient_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_author_id'))

    op.drop_table('facts')
    op.drop_table('share_rules')
    op.drop_table('relationships')
    op.drop_table('memberships')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_author_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('asks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asks_user_id'))
        batch_op.drop_index(batch_op.f('ix_asks_circle_id'))

    op.drop_table('asks')
    op.drop_table('alert_triggers')
    with op.batch_alter_table('product_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_product_events_name'))

    op.drop_table('product_events')
    op.drop_table('password_resets')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_user_id'))

    op.drop_table('llm_calls')
    op.drop_table('feedback')
    op.drop_table('family_circles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_event'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
