"""mfa: totp_secret and mfa_enabled on users

Revision ID: 36b1bc8b0ba6
Revises: 26dfeebc78ce
Create Date: 2026-07-23 20:26:47.068726
"""
from alembic import op
import sqlalchemy as sa


revision = '36b1bc8b0ba6'
down_revision = '26dfeebc78ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(), nullable=True))
        # server_default backfills existing rows; the model default takes over
        batch_op.add_column(
            sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.false())
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
