"""async capture: entry status, applied_rules; action source_entry_id

Revision ID: 705d3c2fe806
Revises: 7a787d5cc31a
Create Date: 2026-07-23 20:45:59.982659
"""
from alembic import op
import sqlalchemy as sa


revision = '705d3c2fe806'
down_revision = '7a787d5cc31a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_entry_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_actions_source_entry_id_journal_entries'), 'journal_entries', ['source_entry_id'], ['id'])

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        # server defaults backfill existing rows (all fully enriched already)
        batch_op.add_column(
            sa.Column('status', sa.String(), nullable=False, server_default='ready')
        )
        batch_op.add_column(
            sa.Column('applied_rules', sa.JSON(), nullable=False, server_default='[]')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('applied_rules')
        batch_op.drop_column('status')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_actions_source_entry_id_journal_entries'), type_='foreignkey')
        batch_op.drop_column('source_entry_id')

    # ### end Alembic commands ###
