"""multi-circle: unique membership per circle-user

Revision ID: 7a787d5cc31a
Revises: 36b1bc8b0ba6
Create Date: 2026-07-23 20:34:36.399330
"""
from alembic import op
import sqlalchemy as sa


revision = '7a787d5cc31a'
down_revision = '36b1bc8b0ba6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_memberships_circle_user', ['circle_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_constraint('uq_memberships_circle_user', type_='unique')

    # ### end Alembic commands ###
